export interface ConsultantProfile {
  name: string;
  title: string;
  company: string;
  website: string;
  email: string;
  phone: string;
  brandColor: string;
  logoUrl?: string;
  reportFooter: string;
}

export const DEFAULT_CONSULTANT_PROFILE: ConsultantProfile = {
  name: "Sakib Hossain",
  title: "Digital Analytics & Conversion Tracking Specialist",
  company: "AnalyticsDev Ultra Advisory",
  website: "https://analyticsdevultra.com",
  email: "sakib@analyticsdevultra.com",
  phone: "+1 (555) 019-2834",
  brandColor: "#059669",
  reportFooter: "Confidential Tracking & Conversion Audit • Generated by AnalyticsDev Ultra",
};

export interface ReportConfig {
  includeExecutiveSummary: boolean;
  includeTechnicalEvidence: boolean;
  includeRecommendations: boolean;
  includeUniversalEvents: boolean;
  includeDataLayer: boolean;
  includeCookies: boolean;
  includeConsent: boolean;
  includeServerSide: boolean;
  mode: "client" | "technical";
}
